apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management-deployment
  labels:
    app: library-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: library-management
  template:
    metadata:
      labels:
        app: library-management
    spec:
      containers:
      - name: library-management
        image: hashtag1229/library-management
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_SERVICE
          valueFrom:
            configMapKeyRef:
              name: library-configmap
              key: database_url
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: library-configmap
              key: mysql-database
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: library-secret
              key: mysql-username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: library-secret
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: library-management-service
spec:
  selector:
    app: library-management
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
